// This file is auto-generated by scripts/generate-routes.mjs
// Do not edit this file directly

function generateQueryString(
  query?: Record<string, string | number | boolean>,
) {
  if (!query) return ''
  const searchParams = new URLSearchParams()
  Object.entries(query).forEach(([key, value]) => {
    if (value !== undefined && value !== null) {
      searchParams.append(key, String(value))
    }
  })
  const queryString = searchParams.toString()
  return queryString ? '?' + queryString : ''
}

export const routes = {
  '/apps/todo/effector': (
    params?: { query?: Record<string, string | number | boolean> } | void,
  ) => {
    if (!params) return '/apps/todo/effector'
    return `/apps/todo/effector${generateQueryString(params?.query)}`
  },
  '/apps/todo/reatom': (
    params?: { query?: Record<string, string | number | boolean> } | void,
  ) => {
    if (!params) return '/apps/todo/reatom'
    return `/apps/todo/reatom${generateQueryString(params?.query)}`
  },
  '/': (
    params?: { query?: Record<string, string | number | boolean> } | void,
  ) => {
    if (!params) return '/'
    return `/${generateQueryString(params?.query)}`
  },
} as const

export type Routes = typeof routes

export type Route = keyof Routes
